### ISSUE TITLE
Wallet app breakpoint

### ISSUE THREAD

**Issue by vinicius-sacramento** [agicommies/commune-ts#112]
![Image](https://github.com/user-attachments/assets/54ff9978-5ab8-4187-83b9-c73218f43a91)

![Image](https://github.com/user-attachments/assets/1675085a-371f-4eb5-9857-b4ec8ee3d9a1)

**Comment by EdSDR** [comment]
@vinicius-sacramento currently there is a condition to display the small wallet address if the user name is > than 10, we can use the same condition but related to screen breakpoints in this case
