### ISSUE TITLE
Community Validator workers

### ISSUE THREAD

**Issue by steinerkelvin** [agicommies/commune-ts#20]
We need to write a long-lived worker service that :

Primary:

- Collects registered modules from the blockchain and stores into the database
- Gets user votes from DB, calculates final weight and sends to blockchain

Secondary:

- Collects module metadata from IPFS

---

- [ ] figure out module metadata
  - module name, description, icon URL, author, homepage URL

**Comment by EdSDR** [comment]
Kelvin: "we basically need to run a thing that constantly polls the blockchain to write in a DB, and constantly queries the DB to send transactions back to the blockchain.
We should have clear workflow on how to deploy services like that that automatically dump logs into Datadog and everything else."

**Comment by steinerkelvin** [comment]
@EdSDR I've elaborated on the linked issue https://github.com/agicommies/infra/issues/11  .-.

**Comment by EdSDR** [comment]
> @EdSDR I've elaborated on the linked issue https://github.com/agicommies/infra/issues/11  .-.

It was a joke sr

**Comment by steinerkelvin** [comment]
https://developers.cloudflare.com/web3/ipfs-gateway/
