### ISSUE TITLE
inbound links broken

### ISSUE THREAD

**Issue by steinerkelvin** [agicommies/commune-ts#21]
Inbound links for proposals and DAOs on Governance Portal like
https://governance.communeai.org/proposal/4 on [Commune DAO incentives -
breakdown of the Governance
update] post are broken.

We need to reestablish the URL structure:

```
- /proposal/<proposal-id>
- /dao/<dao-id>
```

instead of:

```
- /item/proposal/<proposal-id>
- /item/dao/<dao-id>
```

but **without** using the `[...rest]` thing on Next.js.

[Commune DAO incentives - breakdown of the Governance update]:
https://mirror.xyz/0xD80E194aBe2d8084fAecCFfd72877e63F5822Fc5/8SDVs6-C5EaXs4zSSdOTl-OebeSGVQ_ityIECoQtJvI

**Comment by vinicius-sacramento** [comment]
done

**Comment by steinerkelvin** [comment]
@vinicius-sacramento
let's link PR / commit when we finish a issue plz

**Comment by vinicius-sacramento** [comment]
@steinerkelvin sorry, linked now!
