### ISSUE TITLE
New Governance style structure

### ISSUE THREAD

**Issue by EdSDR** [agicommies/commune-ts#28]
[Figma](https://www.figma.com/design/2vfwQAA8E31iWCam3oonlQ/Commune-AI?node-id=6-7978&t=aWc19zykqocQ9lK5-4)
![Image](https://github.com/agicommies/commune-ts/assets/89485015/606487ab-e975-49f3-ade2-d7d2db38aad2)

**Comment by vinicius-sacramento** [comment]
done without background, as we agreed in creating a new ui package to share the animation with the entire monorepo.
