### ISSUE TITLE
Deploy communeX roadmap

### ISSUE THREAD

**Issue by EdSDR** [agicommies/commune-ts#38]
path: `/apps/communex-roadmap`

**Comment by steinerkelvin** [comment]
Should we maybe deploy this at `https://communex.ai/roadmap` and redirect `https://communex.ai/` to `https://communex.ai/roadmap` for now? It doesn't make sense to me to deploy a whole subdomain for a rodmap.

**Comment by EdSDR** [comment]
https://communex-page.pages.dev/ done
