### ISSUE TITLE
Polish/Cleanup on apps and packages

### ISSUE THREAD

**Issue by EdSDR** [agicommies/commune-ts#5]
- [x] Discord Widget
- [x] Better Loading States on proposals
- [x] update stake display on proposal expanded view to use handle_proposal_stake_voted 
- [x] update votes for and votes against function calc / display
- [X] find out what should be on types and utils (subspace)
- [X] check if it's needed separate utils and types from subspace package
- [ ] clean duplicated components <- Moved to a different task so we can close this one

**Comment by EdSDR** [comment]
updated the checkmarks with some stuff that i did with my last commit to main

**Comment by vinicius-sacramento** [comment]
WIP
