### ISSUE TITLE
Cloudflare Monorepo Build Optimizations

### ISSUE THREAD

**Issue by EdSDR** [agicommies/commune-ts#6]
TODO:

- [x] Update package maneger to pnpm, PR with new code: https://github.com/agicommies/commune-ts/pull/26
- [ ] Build optimizations for single projects builds
- [ ] Cashing
- [x] PostgresSQL Database
- [x] Make CI / lint, format and typecheck work on PRs (.github allready set on repo)

**Comment by steinerkelvin** [comment]
We need to figure out how to build a single project with Turbo. Also, caching.

**Comment by EdSDR** [comment]
https://developers.cloudflare.com/pages/configuration/monorepos/

https://developers.cloudflare.com/pages/configuration/build-watch-paths

https://blog.cloudflare.com/pages-workers-integrations-monorepos-nextjs-wrangler

**Comment by DaviPtrs** [comment]
is it done? @steinerkelvin @EdSDR

**Comment by DaviPtrs** [comment]
We're going to move this shit out of Cloudflare pages
